spring:
  kafka:
    bootstrap-servers: 192.168.88.100:9092

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: 1234

    jpa:
      hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.temp.use_jdbc_metadata_defaults: false

app:
  poolSize: 10
  maxPoolSize: 10